#!/bin/bash
#SBATCH --partition=express
#SBATCH --job-name="Minimization"
#SBATCH --error="CV-P-Min.err"
#SBATCH --output="CV-P-Min.out"
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mem-per-cpu=1024
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=hbdean@uab.edu

module load Amber/18-fosscuda-2018a-AmberTools-18-patchlevel-10-8

sander -O -i min-complex.in -p CV-P.prmtop -c CV-P.inpcrd -ref CV-P.inpcrd -o min-complex.out -r CV-P-min.inpcrd -x CV-P-min.mdcrd -inf CV-P-min.mdinfo
