#!/bin/bash
#SBATCH --partition=long
#
# Name your job to make it easier for you to track
#
#SBATCH --job-name=CV-P_MMPBSA
#
# Set your error and output files
#
#SBATCH --error=CV-P_MMPBSA.err
#SBATCH --output=CV-P_MMPBSA.out
#SBATCH --ntasks=1
#
# Even on 32 cpus the scheduler could need the maximum available 150 hours
#
#SBATCH --time=150:00:00
#SBATCH --mem-per-cpu=64000
#
# Set your email address and request notification when the job starts, completes, and/or fails
#
#SBATCH --mail-type=ALL
#SBATCH --mail-user=hbdean@uab.edu

module purge
module load DefaultModules
module load Amber/18-fosscuda-2018a-AmberTools-18-patchlevel-10-8

#ante-MMPBSA.py -p CV-P.prmtop -c complex.prmtop -r receptor.prmtop -l ligand.prmtop -m :1-109 -s :WAT,Na+,Cl-
MMPBSA.py -O -i mmpbsa.in -o CV-P-MMPBSA.dat -cp complex.prmtop -rp receptor.prmtop -lp ligand.prmtop -y CV-P.binpos -eo CV-P-results.csv


