#!/bin/bash
#SBATCH --partition=express
#SBATCH --job-name="CV-T-1-A-BC-md"
#SBATCH --error="CV-T-1-A-BC-md.err"
#SBATCH --output="CV-T-1-A-BC-md.out"
#SBATCH --ntasks=16
#SBATCH --nodes=1
#SBATCH --time=02:00:00
#SBATCH --mem-per-cpu=20024
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ragreer@uab.edu

module purge
module load DefaultModules
module load rc/NAMD/2.12

namd2 +p16 +idlepoll smd.conf > smd.log

