#!/bin/bash
#SBATCH --partition=express
#SBATCH --job-name="3xR47H-T-1-C-AB-md"
#SBATCH --error="3xR47H-T-1-C-AB-md.err"
#SBATCH --output="3xR47H-T-1-C-AB-md.out"
#SBATCH --ntasks=16
#SBATCH --nodes=1
#SBATCH --time=02:00:00
#SBATCH --mem-per-cpu=5024
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ragreer@uab.edu

module purge
module load DefaultModules
module load rc/NAMD/2.12

namd2 +p16 +idlepoll smd.conf > smd.log

