#!/bin/bash
#SBATCH --partition=express
#SBATCH --job-name="Minimiation"
#SBATCH --error="CV-T-Min.err"
#SBATCH --output="CV-T-Min.out"
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mem-per-cpu=1024
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=ragreer@uab.edu

module load Amber/18-fosscuda-2018a-AmberTools-18-patchlevel-10-8

sander -O -i min-complex.in -p CV-T.prmtop -c CV-T.inpcrd -ref CV-T.inpcrd -o min-complex.out -r CV-T-min.inpcrd -x CV-T-min.mdcrd -inf CV-T-min.mdinfo
