#!/bin/bash
#SBATCH --partition=long
#SBATCH --job-name="Enthalpy-01"
#SBATCH --error="Enthalpy-01.err"
#SBATCH --output="Enthalpy-01.out"
#SBATCH --ntasks=1
#SBATCH --time=150:00:00
#SBATCH --mem-per-cpu=10024
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ragreer@uab.edu

#module purge
#module load DefaultModules
module load Amber/18-fosscuda-2018a-AmberTools-18-patchlevel-10-8

#ante-MMPBSA.py -p ../CV-T-SolvI.prmtop -c ../CV-T.prmtop -r ../BC.prmtop -l ../A.prmtop -m :110-327 -s :WAT,Na+,Cl-
#mpiexec -np 32 MMPBSA.py.MPI -O -i MMPBSA.in -o CV-T_MMPBSA.dat -cp ../CV-T.prmtop -rp ../BC.prmtop -lp ../A.prmtop -y ../CV-T.binpos -yr ../CV-T-BC.binpos -yl ../CV-T-A.binpos -eo CV-T-MMPBSA.csv

MMPBSA.py -O -i Enthalpy.in -o Enthalpy-01_MMPBSA.dat -cp ../../Enthalpy-Trajectories/complex.prmtop -rp ../../Enthalpy-Trajectories/receptor.prmtop -lp ../../Enthalpy-Trajectories/ligand.prmtop -y ../../Enthalpy-Trajectories/complex.binpos -yr ../../Enthalpy-Trajectories/receptor.binpos -yl ../../Enthalpy-Trajectories/ligand.binpos -eo Enthalpy-01-MMPBSA.csv
